from enum import StrEnum


class EntityType(StrEnum):
    CHARACTER = "CHARACTER"
    LOCATION = "LOCATION"
    ABILITY = "ABILITY"
    ITEM = "ITEM"
    ORGANIZATION = "ORGANIZATION"
    TITLE = "TITLE"
    SPECIES = "SPECIES"
    EXPRESSION = "EXPRESSION"
    OTHER = "OTHER"


class EntityStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    LOCKED = "LOCKED"


class ProcessingState(StrEnum):
    PENDING = "PENDING"
    DOWNLOADING = "DOWNLOADING"
    DOWNLOADED = "DOWNLOADED"
    ANALYZING = "ANALYZING"
    ANALYZED = "ANALYZED"
    TRANSLATING = "TRANSLATING"
    TRANSLATED = "TRANSLATED"
    VALIDATING = "VALIDATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PAUSED = "PAUSED"


class ValidationStatus(StrEnum):
    OK = "OK"
    WARNING = "WARNING"
    FAILED = "FAILED"


class NovelStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class GlossaryStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    LOCKED = "LOCKED"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

